Traceback (most recent call last):
  File "/Users/sophia/miniconda3/envs/jupyterbook/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/sophia/miniconda3/envs/jupyterbook/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/sophia/miniconda3/envs/jupyterbook/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/sophia/miniconda3/envs/jupyterbook/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/sophia/miniconda3/envs/jupyterbook/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/sophia/miniconda3/envs/jupyterbook/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/Users/sophia/miniconda3/envs/jupyterbook/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/sophia/miniconda3/envs/jupyterbook/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import operator as op
import numpy as np
import pandas as pd
import requests
import param
import panel as pn
import hvplot.pandas
import hvplot.streamz
import holoviews as hv
from holoviews.element.tiles import EsriImagery
from holoviews.selection import link_selections
from datashader.utils import lnglat_to_meters
from streamz.dataframe import PeriodicDataFrame
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m~/miniconda3/envs/jupyterbook/lib/python3.8/site-packages/hvplot/streamz.py[0m in [0;36mpatch[0;34m(name, extension, logo)[0m
[1;32m      6[0m     [0;32mtry[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 7[0;31m         [0;32mimport[0m [0mstreamz[0m[0;34m.[0m[0mdataframe[0m [0;32mas[0m [0msdf[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      8[0m     [0;32mexcept[0m [0mImportError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'streamz'

During handling of the above exception, another exception occurred:

[0;31mImportError[0m                               Traceback (most recent call last)
[0;32m<ipython-input-2-077da6814d32>[0m in [0;36m<module>[0;34m[0m
[1;32m      6[0m [0;32mimport[0m [0mpanel[0m [0;32mas[0m [0mpn[0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0;32mimport[0m [0mhvplot[0m[0;34m.[0m[0mpandas[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 8[0;31m [0;32mimport[0m [0mhvplot[0m[0;34m.[0m[0mstreamz[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      9[0m [0;32mimport[0m [0mholoviews[0m [0;32mas[0m [0mhv[0m[0;34m[0m[0;34m[0m[0m
[1;32m     10[0m [0;32mfrom[0m [0mholoviews[0m[0;34m.[0m[0melement[0m[0;34m.[0m[0mtiles[0m [0;32mimport[0m [0mEsriImagery[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/miniconda3/envs/jupyterbook/lib/python3.8/site-packages/hvplot/streamz.py[0m in [0;36m<module>[0;34m[0m
[1;32m     19[0m     [0mpost_patch[0m[0;34m([0m[0mextension[0m[0;34m,[0m [0mlogo[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     20[0m [0;34m[0m[0m
[0;32m---> 21[0;31m [0mpatch[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/miniconda3/envs/jupyterbook/lib/python3.8/site-packages/hvplot/streamz.py[0m in [0;36mpatch[0;34m(name, extension, logo)[0m
[1;32m      7[0m         [0;32mimport[0m [0mstreamz[0m[0;34m.[0m[0mdataframe[0m [0;32mas[0m [0msdf[0m[0;34m[0m[0;34m[0m[0m
[1;32m      8[0m     [0;32mexcept[0m [0mImportError[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 9[0;31m         raise ImportError('Could not patch plotting API onto streamz. '
[0m[1;32m     10[0m                           'Streamz could not be imported.')
[1;32m     11[0m     [0m_patch_plot[0m [0;34m=[0m [0;32mlambda[0m [0mself[0m[0;34m:[0m [0mhvPlotTabular[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mImportError[0m: Could not patch plotting API onto streamz. Streamz could not be imported.
ImportError: Could not patch plotting API onto streamz. Streamz could not be imported.

